# Generated by Django 5.1.6 on 2026-02-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
    ]
