# Generated by Django 5.1.6 on 2026-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='imports/'),
        ),
    ]
